---
- name: install Apache
  hosts: [enter hosts]
  tasks:
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: latest
  - name: Apache Index file
    copy:
      dest: /var/www/html/index.html
      content: 'Hello World'
      mode: '0644'
  - name: ensure apache is running
      service:
        name: httpd
        state: started
        enabled: true
  - name: Firewall is open to HTTP and is started
    firewalld:
      service: http
      permanent: yes
      state: enabled
...