---
- name: remove Apache
  hosts: [enter hosts]
  tasks:
    - name: ensure apache is stopped
      service:
        name: httpd
        state: stopped
    - name: Remove Apache Index file
      file:
        path: /var/www/html/index.html
        state: absent
    - name: remove the intalled package Apache
      yum:
        name: httpd
        state: absent
    - name: Firewall is closed to HTTP
      firewalld:
        service: http
        permanent: yes
        state: disabled
...